export const embeddable: string;
export const editor: string;
export const editorDiv: string;
export const menuBar: string;
export const output: string;
export const terminal: string;
export const highlightedLine: string;
export const tryDotnetBanner: string;
export const tryDotnetBannerLink: string;
